package com.epic.atemlogin.util.mapping;
// Generated Feb 5, 2019 12:40:42 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "sys_status"
)
public class Status implements java.io.Serializable {

    private String statuscode;
    private String description;
    private Set<Users> usersesForPasswordstatus = new HashSet<Users>(0);
    private Set<Users> usersesForStatus = new HashSet<Users>(0);

    public Status() {
    }

    public Status(String statuscode, String description) {
        this.statuscode = statuscode;
        this.description = description;
    }

    public Status(String statuscode, String description, Set<Users> usersesForPasswordstatus, Set<Users> usersesForStatus) {
        this.statuscode = statuscode;
        this.description = description;
        this.usersesForPasswordstatus = usersesForPasswordstatus;
        this.usersesForStatus = usersesForStatus;
    }

    @Id

    @Column(name = "STATUSCODE", unique = true, nullable = false, length = 16)
    public String getStatuscode() {
        return this.statuscode;
    }

    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 64)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "statusByPasswordstatus")
    public Set<Users> getUsersesForPasswordstatus() {
        return this.usersesForPasswordstatus;
    }

    public void setUsersesForPasswordstatus(Set<Users> usersesForPasswordstatus) {
        this.usersesForPasswordstatus = usersesForPasswordstatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "statusByStatus")
    public Set<Users> getUsersesForStatus() {
        return this.usersesForStatus;
    }

    public void setUsersesForStatus(Set<Users> usersesForStatus) {
        this.usersesForStatus = usersesForStatus;
    }

}
