package com.epic.atemlogin.util.mapping;
// Generated Feb 5, 2019 12:40:42 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "sys_users"
)
public class Users implements java.io.Serializable {

    private String username;
    private Status statusByStatus;
    private Status statusByPasswordstatus;
    private String employeeid;
    private Byte attempts;
    private Date expirydate;
    private String fullname;
    private Date lastloggeddate;
    private String password;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Integer usertype;
    private Integer loginflag;

    public Users() {
    }

    public Users(String username, String password, Date lastupdatedtime, Date createdtime) {
        this.username = username;
        this.password = password;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }

    public Users(String username, Status statusByStatus, Status statusByPasswordstatus, String employeeid, Byte attempts, Date expirydate, String fullname, Date lastloggeddate, String password, String lastupdateduser, Date lastupdatedtime, Date createdtime, Integer usertype, Integer loginflag) {
        this.username = username;
        this.statusByStatus = statusByStatus;
        this.statusByPasswordstatus = statusByPasswordstatus;
        this.employeeid = employeeid;
        this.attempts = attempts;
        this.expirydate = expirydate;
        this.fullname = fullname;
        this.lastloggeddate = lastloggeddate;
        this.password = password;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.usertype = usertype;
        this.loginflag = loginflag;
    }

    @Id

    @Column(name = "USERNAME", unique = true, nullable = false, length = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatusByStatus() {
        return this.statusByStatus;
    }

    public void setStatusByStatus(Status statusByStatus) {
        this.statusByStatus = statusByStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PASSWORDSTATUS")
    public Status getStatusByPasswordstatus() {
        return this.statusByPasswordstatus;
    }

    public void setStatusByPasswordstatus(Status statusByPasswordstatus) {
        this.statusByPasswordstatus = statusByPasswordstatus;
    }

    @Column(name = "EMPLOYEEID", length = 16)
    public String getEmployeeid() {
        return this.employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    @Column(name = "ATTEMPTS")
    public Byte getAttempts() {
        return this.attempts;
    }

    public void setAttempts(Byte attempts) {
        this.attempts = attempts;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EXPIRYDATE", length = 19)
    public Date getExpirydate() {
        return this.expirydate;
    }

    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    @Column(name = "FULLNAME", length = 100)
    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTLOGGEDDATE", length = 19)
    public Date getLastloggeddate() {
        return this.lastloggeddate;
    }

    public void setLastloggeddate(Date lastloggeddate) {
        this.lastloggeddate = lastloggeddate;
    }

    @Column(name = "PASSWORD", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", nullable = false, length = 19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", nullable = false, length = 19)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Column(name = "USERTYPE")
    public Integer getUsertype() {
        return this.usertype;
    }

    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    @Column(name = "LOGINFLAG")
    public Integer getLoginflag() {
        return loginflag;
    }

    public void setLoginflag(Integer loginflag) {
        this.loginflag = loginflag;
    }

}
